04-24-2024 22:00:17 - "<DataAnalyzer>" module begins
04-24-2024 22:00:18 - "<DataProcessor>" module begins
04-24-2024 22:00:18 - "<main>" module begins
04-24-2024 22:00:18 - Starting the program
04-24-2024 22:00:18 - Getting config constants from "Config.py"
04-24-2024 22:00:18 - Creating a dictionary using config constants
04-24-2024 22:00:18 - Completed getting/setting config constants
04-24-2024 22:00:18 - Reading data at: Input/Project_Input_Data.csv
04-24-2024 22:00:22 - User input choice: 4
04-24-2024 22:00:24 - User column name:     def categorical_analysis(self, column_name, r=None):         # Create a DataFrame to store the analysis         categorical_analysis = pd.DataFrame(columns=['unique_values', 'permuations', 'combinations'])                  # Obtain unique values         log_message('Generating unique values..')         unique_values = self.data[column_name].unique()         categorical_analysis['unique_values'] = unique_values          if r is not None:             # Generate permutations             log_message('Generating permutations..')             permutations = list(itertools.permutations(unique_values, r))             categorical_analysis['permutations'] = permutations                      # Generate combinations             log_message('Generating combinations..')             combinations = list(itertools.combinations(unique_values, r))             categorical_analysis['combinations'] = combinations         #                  # Save the analysis to a csv file         categorical_analysis.to_csv(os.path.join('OUTPUT/', f'{column_name}_analysis.csv'), index=False)         log_message(f'Saved categorical analysis to "OUTPUT/{column_name}_analysis.csv')         return categorical_analysis     #
04-24-2024 22:00:27 - User count selection: 
04-24-2024 22:00:27 - Generating unique values..
04-24-2024 22:00:27 - 
---------------------------
An error occurred: '    def categorical_analysis(self, column_name, r=None):         # Create a DataFrame to store the analysis         categorical_analysis = pd.DataFrame(columns=[\'unique_values\', \'permuations\', \'combinations\'])                  # Obtain unique values         log_message(\'Generating unique values..\')         unique_values = self.data[column_name].unique()         categorical_analysis[\'unique_values\'] = unique_values          if r is not None:             # Generate permutations             log_message(\'Generating permutations..\')             permutations = list(itertools.permutations(unique_values, r))             categorical_analysis[\'permutations\'] = permutations                      # Generate combinations             log_message(\'Generating combinations..\')             combinations = list(itertools.combinations(unique_values, r))             categorical_analysis[\'combinations\'] = combinations         #                  # Save the analysis to a csv file         categorical_analysis.to_csv(os.path.join(\'OUTPUT/\', f\'{column_name}_analysis.csv\'), index=False)         log_message(f\'Saved categorical analysis to "OUTPUT/{column_name}_analysis.csv\')         return categorical_analysis     #'
---------------------------
04-24-2024 22:00:28 - User input choice: 5
04-24-2024 22:00:28 - Exiting the program
04-24-2024 22:00:37 - "<DataAnalyzer>" module begins
04-24-2024 22:00:38 - "<DataProcessor>" module begins
04-24-2024 22:00:38 - "<main>" module begins
04-24-2024 22:00:38 - Starting the program
04-24-2024 22:00:38 - Getting config constants from "Config.py"
04-24-2024 22:00:38 - Creating a dictionary using config constants
04-24-2024 22:00:38 - Completed getting/setting config constants
04-24-2024 22:00:38 - Reading data at: Input/Project_Input_Data.csv
04-24-2024 22:00:40 - User input choice: 4
04-24-2024 22:00:48 - User column name: Female_Atheletes
04-24-2024 22:00:50 - User count selection: 10
04-24-2024 22:00:50 - Generating unique values..
04-24-2024 22:00:50 - 
---------------------------
An error occurred: 'Female_Atheletes'
---------------------------
04-24-2024 22:01:18 - User input choice: 4
04-24-2024 22:01:28 - User column name: Female_Athletes
04-24-2024 22:01:32 - User count selection: 10
04-24-2024 22:01:32 - Generating unique values..
04-24-2024 22:01:32 - Generating permutations..
04-24-2024 22:01:32 - 
---------------------------
An error occurred: Expected int as r
---------------------------
